name: Package

on:
  push:
    tags:
      - 'v*'

jobs:
  package-macos:
    runs-on: macos-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          pip3 install pipenv
          pipenv install pyqt5 lxml
          pipenv run pip install pyqt5==5.15.6 lxml
      - name: Build LabelImg
        run: |
          pipenv run make qt5py3
          rm -rf build dist
      - name: Package LabelImg
        run: |
          pipenv run python setup.py py2app || echo "Skipping py2app"
      - name: Archive macOS app
        run: |
          cd dist/ && tar czf labelImg.tgz labelImg.app || echo "No app to archive"
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: macOS-artifact
          path: dist/labelImg.tgz

  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller pyqt5==5.15.6 lxml
      - name: Build LabelImg
        run: |
          pyrcc5 -o libs/resources.py resources.qrc
      - name: Package LabelImg
        run: |
          pyinstaller --hidden-import=pyqt5 --hidden-import=lxml -F -n "labelImgPlusPlus" -c labelImg.py -p ./libs -p ./
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: dist/labelImgPlusPlus.exe

  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller pyqt5==5.15.6 lxml
      - name: Build LabelImg
        run: |
          pyrcc5 -o libs/resources.py resources.qrc
      - name: Package LabelImg
        run: |
          pyinstaller --hidden-import=pyqt5 --hidden-import=lxml -F -n "labelImgPlusPlus" -c labelImg.py -p ./libs -p ./
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-artifact
          path: dist/labelImgPlusPlus
